In [2]:
import numpy as np

data = np.array([1,2,3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [3]:
array_1 = np.array([1,2,3,4,5])
print(array_1)

[1 2 3 4 5]


In [4]:
print(array_1.ndim)
print(array_1.shape)
print(array_1.size)
print(array_1.dtype)

1
(5,)
5
int64


In [5]:
array_2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(array_2)
print(array_2.ndim)
print(array_2.shape)
print(array_2.size)
print(array_2.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)
10
int64


In [6]:
array_3 = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(array_3)

array_4 = array_3.reshape(5,3)
print(array_3)
print(array_4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [7]:
# Methods to create an array fast

print(np.zeros(10))
print(np.zeros(10, dtype=np.int64))
print(np.ones(5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1.]


In [8]:
print(np.arange(2,9,2))

print(np.linspace(0,10,num=5))

[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


In [9]:
# Adding And Sorting elements in a numpy array

array_4 = np.array([2,1,5,10,19,12,8,15])
print(np.sort(array_4))

[ 1  2  5  8 10 12 15 19]


In [10]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6]])

print(x)
print(y)
print(np.concatenate((x,y), axis=0))

[[1 2]
 [3 4]]
[[5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [12]:
# Basic Array Operations

array_5 = np.array([1,2])
array_6 = np.ones(2, dtype=int)

print(array_5)
print(array_6)


print(array_5 + array_6)
print(array_5 - array_6)
print(array_5 * array_6)

[1 2]
[1 1]
[2 3]
[0 1]
[1 2]


In [13]:
# Summation of values
array_7 = np.arange(2,20,2)
print(array_7)
print(array_7.sum())
print(array_7.min())
print(array_7.max())
print(array_7.mean())


[ 2  4  6  8 10 12 14 16 18]
90
2
18
10.0


In [14]:
## Broadcasting

array_8 = np.array([1,3])
print(array_8 * 3.14)

[3.14 9.42]


In [20]:
# Filtering in Numpy Arrays

array_9 = np.array([10,12,8,4,5,1,7,22,40,6])
print(array_9)

print(array_9 > 20)

print(array_9[array_9 > 20])

print(array_9[(array_9 >= 10) & (array_9 <= 30)])

[10 12  8  4  5  1  7 22 40  6]
[False False False False False False False  True  True False]
[22 40]
[10 12 22]


In [24]:
# Save and load numpy objects

array_10 = np.array([1,2,3,4,5,6,7,8])
np.save('array_10', array_10)

print(np.load('array_10.npy'))

np.savetxt('array_10.csv', array_10)

[1 2 3 4 5 6 7 8]


In [27]:
print(np.eye(4))

? np.eye

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Signature:
 np.eye(
    N,
    M=None,
    k=0,
    dtype=<class 'float'>,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference object to allow the creation

In [30]:
a = np.array([[1,2], [3,4]])
B = a.T
print(B)

A = np.array([[1,2,3], [4,5,6]])
C = A.T
print(C)

[[1 3]
 [2 4]]
[[1 4]
 [2 5]
 [3 6]]


In [32]:
arr = np.arange(1,10).reshape(3,3)
print(arr)

result = np.trace(arr)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [34]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

result = np.cross(arr1, arr2)

print(result)

? np.cross

[-3  6 -3]


Signature:        np.cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)
Call signature:   np.cross(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function cross at 0x108985260>
File:            ~/.pyenv/versions/3.12.1/lib/python3.12/site-packages/numpy/_core/numeric.py
Docstring:      
Return the cross product of two (arrays of) vectors.

The cross product of `a` and `b` in :math:`R^3` is a vector perpendicular
to both `a` and `b`.  If `a` and `b` are arrays of vectors, the vectors
are defined by the last axis of `a` and `b` by default, and these axes
can have dimensions 2 or 3.  Where the dimension of either `a` or `b` is
2, the third component of the input vector is assumed to be zero and the
cross product calculated accordingly.  In cases where both input vectors
have dimension 2, the z-component of the cross product is returned.

Parameters
----------
a : array_like
    Components of the first vector(s).
b : array_like
    Components of the second v

In [42]:
# Numpy Assignment 1

import numpy as np

array_1 = np.random.randint(1,100, [5,5])
print(f"Array is: {array_1}")
print(f"Mean is: {array_1.mean()}")
print(f"Standard Deviation is: {array_1.std()}")

Array is: [[56 64 99 60 90]
 [44 11 39 18 67]
 [44 45 23 44 26]
 [ 6 29  6 57 81]
 [34 43 45 75 51]]
Mean is: 46.28
Standard Deviation is: 24.21490450115383


In [48]:
# Numpy Assignment 2

import numpy as np

array_1 = np.identity(5, dtype=np.int64)
print(array_1)
array_2 = array_1 + 5
print(array_2)
array_3 = np.random.randint(1,10, [5,1])
print(array_3)

array_mul = np.multiply(array_2, array_3)
print(array_mul)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[6 5 5 5 5]
 [5 6 5 5 5]
 [5 5 6 5 5]
 [5 5 5 6 5]
 [5 5 5 5 6]]
[[7]
 [4]
 [4]
 [3]
 [2]]
[[42 35 35 35 35]
 [20 24 20 20 20]
 [20 20 24 20 20]
 [15 15 15 18 15]
 [10 10 10 10 12]]


In [49]:
# Numpy Assignment 3

import numpy as np

array_1 = np.random.randint(1,100, [3,3])
array_2 = np.random.randint(1,100, [3,3])
array_mul = np.multiply(array_1, array_2)
print(array_1)
print(array_2)
print(array_mul)

[[78 72 36]
 [78 76 77]
 [14 79 51]]
[[94  6 12]
 [40 98 94]
 [ 7 40 48]]
[[7332  432  432]
 [3120 7448 7238]
 [  98 3160 2448]]


In [53]:
# Numpy Assignment 4

array = np.random.randint(1,1000, [1000])
#print(array)

array_cum = np.cumsum(array)
print(array_cum[9])
print(array_cum[99])
print(array_cum[499])


5370
53077
255491


In [65]:
# Numpy Assignment 5

import numpy as np

array = np.random.randint(1,100, [10,10])
print(array)

#print(array.argmin(keepdims=True))
index_min = array.argmin()
x_axis_min = index_min//10
y_axis_min = index_min % 10

print(x_axis_min, y_axis_min, array.min())

index_max = array.argmax()
x_axis_max = index_max//10
y_axis_max = index_max % 10

print(x_axis_max, y_axis_max, array.max())

[[37 29 73 78 64  9 23 15 41 65]
 [47 52  7 57 55 47  7 21 81 98]
 [80  5 76 15 70 49 28 24 72 38]
 [52 43 86 58 33 41 49 29 58 60]
 [96 43 39 61 40 26 88 34  5 36]
 [72 11  8 45 77 49 62 76  4 97]
 [ 6  5 43 47 87 26 59 56 66 45]
 [ 6  9 94 74 67 85 44 61 46 13]
 [73 54 41 66  4 15  5 80 30 54]
 [39 11 14 89 82 13 29 56 62 87]]
5 8 4
1 9 98


In [82]:
# Numpy Assignment 6

import numpy as np

array = np.random.rand(5,5)
print(array)

array[array == array.max()] = 0.0
print(array)



[[0.09978267 0.47491073 0.81665773 0.68878107 0.24034845]
 [0.32135622 0.27073135 0.09938003 0.17810984 0.48895828]
 [0.15252718 0.71504221 0.30102099 0.10790237 0.62340623]
 [0.37241768 0.48106449 0.5057121  0.74996823 0.99933632]
 [0.67499963 0.32280075 0.16148232 0.49614473 0.57523766]]
[[0.09978267 0.47491073 0.81665773 0.68878107 0.24034845]
 [0.32135622 0.27073135 0.09938003 0.17810984 0.48895828]
 [0.15252718 0.71504221 0.30102099 0.10790237 0.62340623]
 [0.37241768 0.48106449 0.5057121  0.74996823 0.        ]
 [0.67499963 0.32280075 0.16148232 0.49614473 0.57523766]]


In [83]:
# Numpy Assignment 7

import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = A[1:3, 0:2]

B[0, 0] = 100

print(A)

[[  1   2   3]
 [100   5   6]
 [  7   8   9]]


In [90]:
# Numpy Assignment 8

import numpy as np

array = np.random.randint(1,100, 20)
print(array)

print(array[array % 2 == 0].size)
print(array[array % 2 == 1].size)

[10 71 72 31 47 76 66 93 43 42 54 82 31 82 90 24  2  9 62 26]
13
7


In [92]:
import numpy as np

A = np.arange(1, 17).reshape(4, 4)

B = A[:, ::-1]

print(B)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [102]:
# Numpy Assignment 10

import numpy as np

array = np.zeros([8,8], dtype=np.int64)

array[0] = 1
array[-1] = 1
array[:,0] = 1
array[:,-1] = 1
print(array)


[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [110]:
# Pandas Assignment 1

import pandas as pd

data = {

    'Title': ['Inception', 'Dunkirk', 'Interstellar', 'The Prestige', 'Memento'],

    'Director': ['Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan'],

    'Rating': [8.8, 7.9, 8.6, 8.5, 8.4]

}

df = pd.DataFrame(data)
print(df[df['Director'] == 'Christopher Nolan']['Rating'].mean())

8.440000000000001


In [117]:
# Pandas Assignment 2

import pandas as pd

data = {

    'Product': ['Laptop', 'Desktop', 'Tablet', 'Phone', 'Smartwatch'],

    'Price': [25000, 12000, 8000, 22000, 5000]

}

df = pd.DataFrame(data)

print(df[df['Price'] >= 20000].sort_values(by='Price', ascending=False))

  Product  Price
0  Laptop  25000
3   Phone  22000


In [148]:
# Pandas Assignment 3

import pandas as pd

data = {

    'Store': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],

    'Item': ['Apple', 'Banana', 'Orange', 'Grape', 'Apple', 'Banana', 'Orange', 'Grape'],

    'Price': [50, 20, 30, 60, 55, 22, 33, 65],

    'Quantity': [10, 12, 15, 16, 20, 25, 30, 35]

}

df = pd.DataFrame(data)
df['Revenue'] = df['Price'] * df['Quantity']
#print(df)

store_df = df.groupby(by='Store').agg({
    'Price': 'mean',
    'Revenue': 'sum'
})

store_df.reset_index()

store_df.rename(columns={'Price': 'Average Price', 'Revenue': 'Total Revenue'}, inplace=True)

print(store_df)

       Average Price  Total Revenue
Store                              
A              42.00           3040
B              41.75           4025


In [136]:
# Pandas Assignment 4

import pandas as pd

data = {

    'Customer': ['Alice', 'Bob', 'Alice', 'Alice', 'Bob', 'Bob', 'Alice', 'Bob'],

    'Item': ['Pen', 'Pencil', 'Notebook', 'Eraser', 'Pen', 'Pencil', 'Notebook', 'Eraser'],

    'Price': [10, 5, 50, 20, 10, 5, 50, 20],

    'Quantity': [3, 4, 2, 5, 10, 6, 1, 2]

}

df = pd.DataFrame(data=data)

df['Total Expenditure'] = df['Price'] * df['Quantity']
print(df)
df.groupby(by='Customer').agg('Total Expenditure').sum()

  Customer      Item  Price  Quantity  Total Expenditure
0    Alice       Pen     10         3                 30
1      Bob    Pencil      5         4                 20
2    Alice  Notebook     50         2                100
3    Alice    Eraser     20         5                100
4      Bob       Pen     10        10                100
5      Bob    Pencil      5         6                 30
6    Alice  Notebook     50         1                 50
7      Bob    Eraser     20         2                 40


Customer
Alice    280
Bob      190
Name: Total Expenditure, dtype: int64

In [140]:
# Pandas Assignment 5

import pandas as pd

data = {

    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],

    'Temperature': [20, 22, 25, 27, 30, 32, 35, 34, 30, 28, 24, 21]

}

df = pd.DataFrame(data)

print(df[df['Temperature'] == df['Temperature'].max()]['Month'])

6    Jul
Name: Month, dtype: object


In [141]:
# Pandas Assigment 6

data = {

    'Category': ['Fruit', 'Vegetable', 'Fruit', 'Vegetable', 'Fruit', 'Vegetable'],

    'Name': ['Apple', 'Carrot', 'Banana', 'Potato', 'Grape', 'Onion'],

    'Price': [2, 1, 1.5, 0.5, 3, 1],

    'Quantity': [10, 20, 15, 30, 5, 40]

}

df = pd.DataFrame(data)

fruits = df[df['Category'] == 'Fruit']

total_fruit_value = fruits['Price'].sum() * fruits['Quantity'].sum()

print(total_fruit_value)

195.0


In [142]:
# Pandas Assignment 7

import pandas as pd

data = {

    'Name': ['Alice', 'Bob', 'Charlie', 'David'],

    'Age': [25, 30, 35, 40],

    'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']

}

df = pd.DataFrame(data)

result = df[df['Age'] >= 30].sort_values(by='Age', ascending=False).iloc[0]['City']

print(result)

Chicago


In [143]:
# Pandas Assignment 8

import pandas as pd

data = {

    'Product': ['A', 'B', 'C', 'A', 'B', 'C'],

    'Price': [100, 200, 300, 150, 250, 350],

    'Quantity': [10, 5, 7, 12, 8, 5]

}

df = pd.DataFrame(data)

total_revenue = (df['Price'] * df['Quantity']).sum()

average_price = df['Price'].mean()

print(total_revenue, average_price)

9650 225.0


In [145]:
# Pandas Assignment 9
import pandas as pd

data = {

    'Customer': ['Alice', 'Bob', 'Alice', 'Alice', 'Bob', 'Bob', 'Alice', 'Bob'],

    'Item': ['Pen', 'Pencil', 'Notebook', 'Eraser', 'Pen', 'Pencil', 'Notebook', 'Eraser'],

    'Price': [10, 5, 50, 20, 10, 5, 50, 20],

    'Quantity': [3, 4, 2, 5, 10, 6, 1, 2]

}

df = pd.DataFrame(data=data)

df['Total Amount'] = df['Price'] * df['Quantity']
#print(df)

print(f"Total Amount Spent: {df['Total Amount'].sum()}")

print(df.groupby(by='Item').agg('Total Amount').sum())

Total Amount Spent: 470
Item
Eraser      140
Notebook    150
Pen         130
Pencil       50
Name: Total Amount, dtype: int64


In [147]:
# Pandas Assignment 10

import pandas as pd

data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    'City_A_Temp': [20, 22, 25, 27, 30, 32, 35, 34, 30, 28, 24, 21],
    'City_B_Temp': [10, 12, 15, 17, 20, 22, 25, 24, 20, 18, 14, 11]
}

df = pd.DataFrame(data)

df['Temp diff b/w cities'] = abs(df['City_A_Temp'] - df['City_B_Temp'])

print(df['Temp diff b/w cities'].mean())

10.0
